### ISSUE TITLE
Refactor the React chapters with Kandy Korner

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/client-side-mastery#102]
Instead of just having the student copy pasta code from the lesson plans into their own code base and change a few variables, add exercises that have them build a separate app named Kandy Korner.

Resources/features include

1. Candy items (list/add)
1. Candy types (list/add)
1. Store locations (list)
1. Employees (list/add/remove/edit)
1. Employees by store

**Comment by JoeShep** [comment]
💯
