### ISSUE TITLE
API actions should disable buttons

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/client-side-mastery#119]
Add a state variable to every component that has a button that triggers an API call that changes the state of the application. The `disabled` attribute of the button should be bound to that state variable. The state variable (e.g. `buttonEnabled`) would toggle `true` or `false`.  As soon as user clicks on button, toggle state variable to false.

**Comment by brendalong** [comment]
Example ```
<button style={{ width: '100%' }} id="save" onClick={this.saveNote} disabled={this.state.savenow ? false : true}>Save Note</button>
```
