### ISSUE TITLE
Extra single quotation mark ['] in the [Oh My Zsh] section on #4 step.  

### ISSUE THREAD

**Issue by davidb-github** [nashville-software-school/client-side-mastery#190]
Issue:
There is an extra single quote ['] in the [Oh My Zsh] section on the #4 step the command 
alias hs="serve -l 8080"' >> ~/.zshrc
Should this be?: alias hs="serve -l 8080" >> ~/.zshrc

Where:
https://github.com/nashville-software-school/client-side-mastery/blob/master/book-1-martins-aquarium/chapters/GETTING_STARTED_MAC.md

Impact:
This causes .zsh to go into quote mode after entering the command which seems unintentional.

**Comment by Scott47** [comment]
This is a single quote if for the echo command. The single quotes keep the literal value of every character inside of the them so that `alias gs="git status" alias hs="serve -l 8080"` is written to your `.zshrc` file.
