### ISSUE TITLE
Handle main/master change in git/github in chapters

### ISSUE THREAD

**Issue by BlaiseGratton** [nashville-software-school/client-side-mastery#234]
It may be worth noting when git is introduced the shift that git/github made in 2020 to deprecate the default initialization branch being called `master` to `main`. I'll open PRs for the text content accordingly but the images in some of the chapter markdown may need to be regenerated.

**Comment by stevebrownlee** [comment]
Initial fix made in following commit:

https://github.com/nashville-software-school/client-side-mastery/commit/866e28b82c821b677c9a1ad33b2643710db25745

For now, removed all images and replaced with a textual walkthrough
