### ISSUE TITLE
Book 6 Chapter 12 and 13 duplicate instructions

### ISSUE THREAD

**Issue by sorachung** [nashville-software-school/client-side-mastery#301]
The Practice portion of [Chapter 12](https://github.com/nashville-software-school/client-side-mastery/blob/cohort-53/book-6-honey-rae-repairs/chapters/HONEY_ROUTE_PARAMS.md) is the same as all of [Chapter 13](https://github.com/nashville-software-school/client-side-mastery/blob/cohort-53/book-6-honey-rae-repairs/chapters/HONEY_EMPLOYEE_DETAILS.md)

**Comment by stevebrownlee** [comment]
Fixed in commit [f4ba282faa8aafa5b7ae71da6b6c37975c8e01e1](https://github.com/nashville-software-school/client-side-mastery/commit/f4ba282faa8aafa5b7ae71da6b6c37975c8e01e1). Will be merged at end of cohort.
