### ISSUE TITLE
book-1-martins-aquarium/chapters/GIT_UPGRADE.md

### ISSUE THREAD

**Issue by gradyrobbins** [nashville-software-school/client-side-mastery#307]
The current state of instructions in GIT_UPGRADE.md  are:

> # UPGRADE GIT
> 
> The commands below are for upgrading git on your local machine if you do not have a version greater than 2.27.
> 
> ### Mac Users
> 
> ```$ brew install git```
> 

<hr/>

Wondering whether ~~brew install git~~  &rarr;  ``` brew upgrade git``` ?

**Comment by stevebrownlee** [comment]
No, for new students, it's an install, not an upgrade
