### ISSUE TITLE
Command line basics uses git for alias examples, but git hasn't been covered yet

### ISSUE THREAD

**Issue by JoeShep** [nashville-software-school/client-side-mastery#58]
Wondering if it's intimidating/confusing to the students to practice making aliases for commands they don't understand. Would they be better served to instead make aliases for `ls -l` or `../` for example?

**Comment by stevebrownlee** [comment]
You can suggest they make any aliases you want. That chapter is for the instructor to reference as they work through Book 2. If you want to skip some parts of it on the first day, then come to material after you've covered git.
