### ISSUE TITLE
BEM examples seem counter to principles

### ISSUE THREAD

**Issue by JoeShep** [nashville-software-school/client-side-mastery#60]
The [BEM example](https://github.com/nashville-software-school/client-side-mastery/blob/master/book-2-the-novice/chapters/HTML_COMPONENTS.md#intelligent-css-class-naming-conventions) looks to me to be inside out. For example, the CSS-Tricks article linked in the README describes it thusly:
> "[A] block should be thought of as a parent. Child items, or elements, can be placed inside and these are denoted by two underscores following the name of the block like .btn__price { }. Finally, modifiers can manipulate the block so that we can theme or style that particular component without inflicting changes on a completely unrelated module. This is done by appending two hyphens to the name of the block just like btn—orange"  

Their example is 
```
<a class="btn btn--big btn--orange" href="http://css-tricks.com">
  <span class="btn__price">$9.99</span>
  <span class="btn__text">Subscribe</span>
</a>
```
But our example doesn't align with this:
```
<nav class="navigation">
    <!-- Navigation Link List Component -->
    <ul class="list list--navigation">
        <!-- Navigation Link Component -->
        <li class="listitem--navigation">
            <a href="index.html">Home</a>
        </li>
        <li class="listitem--navigation">
            <a href="careers.html">Careers</a>
        </li>
        <li class="listitem--navigation">
            <a href="locations.html">Locations</a>
        </li>
    </ul>
</nav>
```
To my eye, if this was like the CSS-Tricks example it would look like this:
```
<nav class="navigation">
    <!-- Navigation Link List Component -->
    <ul class="list navigation__list">
        <!-- Navigation Link Component -->
        <li class="navigation_listitem">
            <a href="index.html">Home</a>
        </li>
        <li class="navigation_listitem">
            <a href="careers.html">Careers</a>
        </li>
        <li class="navigation_listitem">
            <a href="locations.html">Locations</a>
        </li>
    </ul>
</nav>
```
This would make `navigation` the parent element, and the nested elements would be marked as its children by giving them the parent's name followed by their specific element description. There are no modifiers, so none of them use the double dash. But if we wanted to designate the first list item as the first for some reason, we would name it `navigation_listitem—first`, or if we wanted to describe its contents it could be `navigation_listitem—home`.  

Thoughts?

**Comment by brendalong** [comment]
I agree.

If following the BEM you quoted, be sure to include the double underscore
in your example (missing one):
<li class="navigation_listitem">
