### ISSUE TITLE
Add details for Windows subsystem users

### ISSUE THREAD

**Issue by gregkorte** [nashville-software-school/client-side-mastery#64]
1. Commands for creating path in zsh or bash file to define root
1. Introduction to screen (for multiple instances)
1. Commands for implementing screen

   -Commands to navigate screen
   -Function in zsh or bash to check if an instance of screen is currently running

1. Issues with ssh agent, having to enter password every time they push to github
1. Node installation for correct pathing in vs code for quokka
1. Node version that comes with Ubuntu may need to be updated
  - `$node -v v0.6.12`
  - `sudo npm cache clean -f `
  - `sudo npm install -g n`
  - `sudo n stable`
  - `$node -v v0.8.11`

@Levi-Schubert: If you can think of any other details we can add them to this ticket

**Comment by stevebrownlee** [comment]
Windows sub-system was more trouble than it was worth. Sticking with Git Bash for the time being.
