### ISSUE TITLE
chown permissions to the .config file in the home directory 

### ISSUE THREAD

**Issue by Jennabsol** [nashville-software-school/client-side-mastery#66]
sudo chown [user] [path to file/directory] 
Some Mac users did not have the correct permissions on ther .config file.
They would get an error while using `git status`.

**Comment by Jennabsol** [comment]
sudo chown -R $USER:$(id -gn $USER) /Users/[username]/.config 
to give root permissions!

**Comment by stevebrownlee** [comment]
Windows sub-system was more trouble than it was worth. Sticking with Git Bash for the time being.
