### ISSUE TITLE
ServiceWorker changes

### ISSUE THREAD

**Issue by braddavistech** [nashville-software-school/client-side-mastery#82]
When I use create-react-app and look into the serviceWorker.js , I had to change  export function register(config) to export default function register(config) to make it work. I also had to modify index.js to import register from './serviceWorker' to make things operate correctly. Otherwise, it throws errors that it can't find the files or can't find export default.

**Comment by stevebrownlee** [comment]
@braddavistech Could you specify exactly what in the course needs to be changed?  Also, feel free to make the change if you wish, and submit a PR
